import os

os.chdir(__file__[:(__file__.rfind('\\'))])
errorsFile = open("errors.txt", "r")
errorsData = str(errorsFile.read()).splitlines()
output = ""
def addline(line = ""):
    global output
    output += line + "\n"
addline("//This file was generated by generators/idthandlers.py")
addline("#include \"utils.h\"")
addline("#include \"idthandlerscommon.h\"")
addline("#include \"irqhandlers.h\"")
for i in range(len(errorsData)):
    e = errorsData[i]
    addline("void exceptionHandler" + str(i) + "() {")
    if e != '#':
        addline("\tprintl(\"" + e  + "\");")
        addline("\texceptionHandlerCommon();")
    else:
        addline("\t//This handler is for a reserved interrupt, and therefore only exists for consistency")
    addline("}")
    addline()
open("../idthandlers.h", "w").write(output)